apiVersion: apps/v1
kind: Deployment

metadata:
  name: {}-deployment
  namespace: mc-lab
  labels:
    user: {}

spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx
  template:
    metadata:
      labels:
        k8s-app: nginx
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: k8s-haosu-10.sdsc.optiputer.net
      containers:
      - name: container
        image: jerrypiglet/rui_conda_inverse:public
        args: ["sleep", "infinity"]
        resources:  
          requests:
            cpu: "100m"
            memory: "2Gi"
            # nvidia.com/gpu: 1
          limits:
            cpu: "16"
            memory: "16Gi"
            # nvidia.com/gpu: 1
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: openroomsindept
          mountPath: /openroomsindept
        - name: {}data
          mountPath: /{}data

      volumes:
      - name: ruidata
        persistentVolumeClaim:
            claimName: ruidata
      - name: dshm
        emptyDir:
          medium: Memory

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/group
                operator: In
                values:
                - haosu
