DATASET:
  num_workers: 16 
MODEL_BRDF:
  enable: True
  load_pretrained_pth: False
  enable_BRDF_decoders: True
  enable_list: al_ro_no_de
  loss_list: al_ro_no_de
DATA:
  data_read_list: al_ro_no_de
  im_height: 240
  im_width: 320
  if_load_png_not_hdr: False
DEBUG:
  if_dump_perframe_BRDF: False
SOLVER:
  ims_per_batch: 8
TEST:
  ims_per_batch: 8